### ISSUE TITLE
Mixed tabs and spaces

### ISSUE THREAD

**Issue by AndreaCogliati** [textmate/cython.tmbundle#3]
The bundle seems to default to tabs for indentation (contrary to the Python bundle and PEP-8)

**Comment by sorbits** [comment]
This bundle does not set tab settings, but the defaults in TextMate has it set to soft tabs for Python: https://github.com/textmate/textmate/blob/d2979e29178631975ee348b4fddc0664464b165d/Applications/TextMate/resources/Default.tmProperties#L40

Please see https://macromates.com/support and https://github.com/textmate/textmate/wiki/Reverting-To-Defaults for troubleshooting help.

**Comment by sorbits** [comment]
Sorry, I missed that this was Cython and not Python.

Nonetheless, please see https://macromates.com/support
